/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface CloudflareEnv ./cloudflare-env.d.ts` (hash: 8ae2d676a7b4b1a5a998c6ac0e81595c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./_fresh/server");
	}
	interface Env {
		ASSETS: Fetcher;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
